### ISSUE TITLE
Google colab `Unrecognized keyword arguments passed to Conv2DTranspose: {'groups': 1}` error

### ISSUE THREAD

**Issue by metabusdriver21** [AVAuco/deeparuco#2]
Probably there is some versioning issue?

**Comment by rafabs97** [comment]
That's right, recent versions of Keras don’t support that argument for Conv2DTranspose anymore. Since our models were trained using an older version (2.11.0), they still depend on it. To make things easier, we’ve added pip and conda requirement files to the repo and also fixed up the Colab demo so it works again. Thanks for your patience, and sorry for the inconvenience! If you spot anything else that’s not working, feel free to open a new issue :)
